Northwest_Prototype/Models/Tests.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Northwest_Prototype.Models
{
    [Table("Tests")]
    public class Tests
    {

        [Key]
        [Required]
        public int TestID { get; set; }

        [Required(ErrorMessage = "Please Enter Name for Test")]
        [Display(Name = "Test")]
        public string TestName { get; set; }

        [Required(ErrorMessage = "Please Enter a Description for Test")]
        [Display(Name = "Test Description")]
        public string TestDesc { get; set; }

        [Required(ErrorMessage = "Please Enter the Cost for Test")]
        [Display(Name = "Test Buisness Price")]
        public decimal TestPriceBusi { get; set; }

        [Required(ErrorMessage = "Please Enter a Price for Test")]
        [Display(Name = "Test Customer Price")]
        public decimal TestPriceCust { get; set; }

        public virtual ICollection<AssayToTest> AssayToTests { get; set; }
    }
}

Northwest_Prototype/Controllers/QuotesController.cs
using Northwest_Prototype.DAL;
using Northwest_Prototype.Models;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Northwest_Prototype.Controllers
{
    public class QuotesController : Controller
    {
        private NorthwestDevContext db = new NorthwestDevContext();

        // GET: Assays
        public ActionResult Index()
        {
            return View(db.assays.ToList());
        }

        // GET: Assays/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assay assay = db.assays.Find(id);
            if (assay == null)
            {
                return HttpNotFound();
            }
            var Results = from b in db.tests
                          select new
                          {
                              b.TestID,
                              b.TestName,
                              b.TestPriceCust,

                              Checked = ((from ab in db.assayToTests
                                          where (ab.AssayID == id) & (ab.TestID == b.TestID)
                                          select ab).Count() > 0)


                          };
            var MyViewModel = new AssayViewModel();
            MyViewModel.AssayID = id;
            MyViewModel.AssayName = assay.AssayName;
            MyViewModel.AssayProtocol = assay.AssayProtocol;
            MyViewModel.EstDayDuration = assay.EstDayDuration;

            var MyCheckBoxList = new List<CheckBoxViewModel>();
            decimal TotalPrice = 0;
            foreach (var item in Results)
            {
                MyCheckBoxList.Add(new CheckBoxViewModel { Id = item.TestID, Name = item.TestName, Checked = item.Checked, Price = item.TestPriceCust });
                if (item.Checked)
                {
                    TotalPrice = TotalPrice + (item.TestPriceCust + (MyViewModel.EstDayDuration * (8 * 40)));
                }
            }

            MyViewModel.Tests = MyCheckBoxList;
            MyViewModel.TotalPrice = TotalPrice;
            return View(MyViewModel);
        }

        // GET: Assays/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Assays/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AssayID,AssayName,AssayProtocol,EstDayDuration")] Assay assay)
        {
            if (ModelState.IsValid)
            {
                db.assays.Add(assay);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(assay);
        }

        // GET: Assays/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assay assay = db.assays.Find(id);
            if (assay == null)
            {
                return HttpNotFound();
            }

            var Results = from b in db.tests
                          select new
                          {
                              b.TestID,
                              b.TestName,

                              Checked = ((from ab in db.assayToTests
                                          where (ab.AssayID == id) & (ab.TestID == b.TestID)
                                          select ab).Count() > 0)


                          };
            var MyViewModel = new AssayViewModel();
            MyViewModel.AssayID = id;
            MyViewModel.AssayName = assay.AssayName;
            MyViewModel.AssayProtocol = assay.AssayProtocol;
            MyViewModel.EstDayDuration = assay.EstDayDuration;

            var MyCheckBoxList = new List<CheckBoxViewModel>();

            foreach (var item in Results)
            {
                MyCheckBoxList.Add(new CheckBoxViewModel { Id = item.TestID, Name = item.TestName, Checked = item.Checked });
            }

            MyViewModel.Tests = MyCheckBoxList;

            return View(MyViewModel);
        }

        // POST: Assays/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AssayViewModel assay)
        {
            if (ModelState.IsValid)
            {
                var MyAssay = db.assays.Find(assay.AssayID);


                MyAssay.AssayName = assay.AssayName;
                MyAssay.AssayProtocol = assay.AssayProtocol;
                MyAssay.EstDayDuration = assay.EstDayDuration;

                foreach (var item in db.assayToTests)
                {
                    if (item.AssayID == assay.AssayID)
                    {
                        db.Entry(item).State = System.Data.Entity.EntityState.Deleted;
                    }
                }

                foreach (var item in assay.Tests)
                {
                    if (item.Checked)
                    {

                        db.assayToTests.Add(new AssayToTest() { AssayID = assay.AssayID, TestID = item.Id });
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(assay);
        }

        // GET: Assays/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assay assay = db.assays.Find(id);
            if (assay == null)
            {
                return HttpNotFound();
            }
            return View(assay);
        }

        // POST: Assays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Assay assay = db.assays.Find(id);
            db.assays.Remove(assay);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Northwest_Prototype/Controllers/WorkOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Northwest_Prototype.DAL;
using Northwest_Prototype.Models;

namespace Northwest_Prototype.Controllers
{
    public class WorkOrdersController : Controller
    {
        private NorthwestDevContext db = new NorthwestDevContext();

        // GET: WorkOrders
        //WorkOrders view for Sales Reps
        public ActionResult Index()
        {
            List<WorkOrders> lstWorkOrders = db.workOrders.ToList();
            //lstWorkOrders.Sort((x, y) => DateTime.Compare(x.DateDue, y.DateDue));
            return View(lstWorkOrders);
        }

        // GET: WorkOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrders workOrders = db.workOrders.Find(id);
            if (workOrders == null)
            {
                return HttpNotFound();
            }
            return View(workOrders);
        }

        // GET: WorkOrders/Create
        public ActionResult Create()
        {
            ViewBag.Customers = db.customers.ToList();
            ViewBag.Employees = db.employees.ToList();
            ViewBag.Assays = db.assays.ToList();
            ViewBag.Compounds = db.compounds.ToList();
            ViewBag.OrderStatus = db.orderStatuses.ToList();

            return View();
        }

        // POST: WorkOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Customer, Assay, Employee, Compound, OrderStatus, DateDue, QuotePrice,Discount,Billed,Paid,Comments,Quantity,DateReceived,ReceivedBy,CompoundWeight_Client,CompoundWeight_Actual,CompoundMass,DateTimeConfirmation,MTD")] WorkOrders workOrders)
        { //[Bind(Include = "WorkOrderID, Customer.CustomerID, DateDue,Status,QuotePrice,Discount,Billed,Paid,Comments,Quantity,DateReceived,ReceivedBy,CompoundWeight_Client,CompoundWeight_Actual,CompoundMass,DateTimeConfirmation,MTD")]
            ///* Customer, Assay, Employee, Compound,
            workOrders.Customer = db.customers.Find(workOrders.Customer.CustomerID);
            workOrders.Assay = db.assays.Find(workOrders.Assay.AssayID);
            workOrders.Employee = db.employees.Find(workOrders.Employee.EmployeeID);
            workOrders.Compound = db.compounds.Find(workOrders.Compound.CompoundID);
            workOrders.OrderStatus = db.orderStatuses.Find(workOrders.OrderStatus.OrderStatusID);
            workOrders.ResultsID = 3;

            ModelState.Remove("Customer.CustFirstName");
            ModelState.Remove("Customer.CustLastName");
            ModelState.Remove("Customer.CustAdd1");
            ModelState.Remove("Customer.CustCity");
            ModelState.Remove("Customer.CustState");
            ModelState.Remove("Customer.CustZip");
            ModelState.Remove("Customer.CustCountry");
            ModelState.Remove("Customer.CustPhone");
            ModelState.Remove("Customer.CustEmail");
            ModelState.Remove("Assay.AssayName");
            ModelState.Remove("Compound.CompoundDesc");
            ModelState.Remove("OrderStatus.OrderStatusTitle");
            ModelState.Remove("OrderStatus.OrderStatusDesc");
            ModelState.Remove("Employee.EmpFirstName");
            ModelState.Remove("Employee.EmpLastName");
            ModelState.Remove("Employee.EmpState");
            ModelState.Remove("Employee.EmpAddress1");
            ModelState.Remove("Employee.EmpCity");
            ModelState.Remove("Employee.EmpZip");
            ModelState.Remove("Employee.EmpCountry");
            ModelState.Remove("Employee.EmpPhone");
            ModelState.Remove("Employee.EmpEmail");

            if (ModelState.IsValid)
            {  
                db.workOrders.Add(workOrders);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.Customers = db.customers.ToList();
            ViewBag.Employees = db.employees.ToList();
            ViewBag.Assays = db.assays.ToList();
            ViewBag.Compounds = db.compounds.ToList();
            ViewBag.OrderStatus = db.orderStatuses.ToList();

            return View(workOrders);
        }

        public ActionResult Tests(int iCode)
        {
            //find the work order object that they clicked on
            WorkOrders oWorkOrder = db.workOrders.ToList().Find(x => x.LT_Number == iCode);

            //list of all the reviews
            List<WorkOrders_Tests> lstTests = db.workOrders_Tests.ToList();

            //empty list that will contain all reviews for specific restaurants
            List<WorkOrders_Tests> specTests = new List<WorkOrders_Tests>();

            for (var iCount = 0; iCount < lstTests.Count; iCount++)
            {
                //if the review has same restaurant code as the restaurant clicked on, add that review to specific list
                if (lstTests[iCount].WorkOrders.LT_Number == oWorkOrder.LT_Number)
                {
                    specTests.Add(lstTests[iCount]);
                }
            }

            //pass to models to view with tuple.  the restaurant object for summary info, and specific reviews for that restaurant
            var model = Tuple.Create<WorkOrders, IEnumerable<WorkOrders_Tests>>(oWorkOrder, specTests);


            return View(model);
        }

        public ActionResult AddTest(int iCode)
        {
            
            ViewBag.Employees = db.employees.ToList();
            ViewBag.Tests = db.tests.ToList();
            ViewBag.LT = iCode;

            return View();
        }

        [HttpPost]
        public ActionResult AddTest([Bind(Include = "Tests, Employee, WorkOrders, CompoundSequenceCode, Required, DateScheduled, DateCompleted, RerunNeeded, AdditionalTests, Approved")] WorkOrders_Tests newTest)
        {
            newTest.Tests = db.tests.Find(newTest.Tests.TestID);
            newTest.Employee = db.employees.Find(newTest.Employee.EmployeeID);
            newTest.WorkOrders = db.workOrders.Find(newTest.WorkOrders.LT_Number);

            ModelState.Remove("Tests.TestName");
            ModelState.Remove("Tests.TestDesc");
            ModelState.Remove("Employee.EmpFirstName");
            ModelState.Remove("Employee.EmpLastName");
            ModelState.Remove("Employee.EmpState");
            ModelState.Remove("Employee.EmpAddress1");
            ModelState.Remove("Employee.EmpCity");
            ModelState.Remove("Employee.EmpZip");
            ModelState.Remove("Employee.EmpCountry");
            ModelState.Remove("Employee.EmpPhone");
            ModelState.Remove("Employee.EmpEmail");

            if (ModelState.IsValid)
            {
                db.workOrders_Tests.Add(newTest);
                db.SaveChanges();

                return RedirectToAction("Tests", new { iCode = newTest.WorkOrders.LT_Number });
            }
            else
            {
                ViewBag.Employees = db.employees.ToList();
                ViewBag.Tests = db.tests.ToList();

                return View(newTest);
            }
        }


        // GET: WorkOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrders workOrders = db.workOrders.Find(id);
            if (workOrders == null)
            {
                return HttpNotFound();
            }
            return View(workOrders);
        }

        // POST: WorkOrders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WorkOrderID,DateDue,Status,QuotePrice,Discount,Billed,Paid,Comments,Quantity,DateReceived,ReceivedBy,CompoundWeight_Client,CompoundWeight_Actual,CompoundMass,DateTimeConfirmation,MTD")] WorkOrders workOrders)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workOrders).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(workOrders);
        }

        // GET: WorkOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrders workOrders = db.workOrders.Find(id);
            if (workOrders == null)
            {
                return HttpNotFound();
            }
            return View(workOrders);
        }

        // POST: WorkOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkOrders workOrders = db.workOrders.Find(id);
            db.workOrders.Remove(workOrders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Quote()
        {
            return View();
        }

        
        public ActionResult EditTest(int? iCode)
        {
            ViewBag.Employees = db.employees.ToList();
            ViewBag.Tests = db.tests.ToList();
            

            if (iCode == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

Northwest_Prototype/Views/WorkOrders/Delete.cshtml
@model Northwest_Prototype.Models.WorkOrders

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkOrders</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateDue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuotePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuotePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Billed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Billed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReceived)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReceived)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceivedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceivedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompoundWeight_Client)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompoundWeight_Client)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompoundWeight_Actual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompoundWeight_Actual)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompoundMass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompoundMass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeConfirmation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeConfirmation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MTD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MTD)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-default" })
        </div>
    }
</div>

Northwest_Prototype/Views/WorkOrders/Quote.cshtml
@{
    ViewBag.Title = "Quote";
}

<h2>Quote</h2>

Northwest_Prototype/Views/WorkOrders/Tests.cshtml
@model Tuple<Northwest_Prototype.Models.WorkOrders, IEnumerable<Northwest_Prototype.Models.WorkOrders_Tests>>
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "ShowTests";
}


<div class="jumbotron jumbotron-test-data">
    <div class="container h-100">
        <div>

            <h1 style="text-decoration: underline">@Html.DisplayFor(model => model.Item1.Customer.CustFirstName) @Html.DisplayFor(model => model.Item1.Customer.CustLastName)</h1>
            <span style="font-size: 20px;"><strong>@Html.DisplayNameFor(model => model.Item1.LT_Number):  @Html.DisplayFor(model => model.Item1.LT_Number) </strong></span><br />
            <div style="font-size: 17px; text-align: left; column-count: 3">
                
                @{ var parameter = Model.Item1.DateDue.ToShortDateString();}
                @Html.DisplayNameFor(model => model.Item1.DateDue): <strong>@Html.DisplayFor(model => parameter) </strong><br />

                @Html.DisplayNameFor(model => model.Item1.Assay.AssayName): <strong> @Html.DisplayFor(model => model.Item1.Assay.AssayName)</strong><br />
                @Html.DisplayNameFor(model => model.Item1.Assay.EstDayDuration): <strong> @Html.DisplayFor(model => model.Item1.Assay.EstDayDuration) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.OrderStatusID): <strong> @Html.DisplayFor(model => model.Item1.OrderStatus.OrderStatusDesc) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.QuotePrice): <strong> @Html.DisplayFor(model => model.Item1.QuotePrice)  </strong><br />
                @Html.DisplayNameFor(model => model.Item1.Discount) : <strong> @Html.DisplayFor(model => model.Item1.Discount) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.Billed): <strong> @Html.DisplayFor(model => model.Item1.Billed) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.Paid): <strong> @Html.DisplayFor(model => model.Item1.Paid) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.Comments): <strong> @Html.DisplayFor(model => model.Item1.Comments) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.Quantity): <strong> @Html.DisplayFor(model => model.Item1.Quantity)</strong><br />
                @{ var datereceived = Model.Item1.DateReceived.ToShortDateString();}
                @Html.DisplayNameFor(model => model.Item1.DateReceived): <strong> @Html.DisplayFor(model => datereceived) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.ReceivedBy): <strong> @Html.DisplayFor(model => model.Item1.ReceivedBy) @*@Html.DisplayFor(model => model.Item1.receivedBy.EmpLastName)*@</strong><br />
                @Html.DisplayNameFor(model => model.Item1.CompoundWeight_Client): <strong> @Html.DisplayFor(model => model.Item1.CompoundWeight_Client) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.CompoundWeight_Actual): <strong> @Html.DisplayFor(model => model.Item1.CompoundWeight_Actual) </strong><br />
                @Html.DisplayNameFor(model => model.Item1.CompoundMass): <strong> @Html.DisplayFor(model => model.Item1.CompoundMass) </strong><br />
                @{ var dateconfirmation = Model.Item1.DateTimeConfirmation.ToShortDateString();}
                @Html.DisplayNameFor(model => model.Item1.DateTimeConfirmation): <strong> @Html.DisplayFor(model => dateconfirmation)</strong><br />
                @Html.DisplayNameFor(model => model.Item1.MTD): <strong> @Html.DisplayFor(model => model.Item1.MTD)</strong><br /><br />
                @Html.DisplayNameFor(model => model.Item1.Results.QualResult): <strong> @Html.DisplayFor(model => model.Item1.Results.QualResult)</strong><br />
                @Html.DisplayNameFor(model => model.Item1.Results.QuantResultRaw): <strong> @Html.DisplayFor(model => model.Item1.Results.QuantResultRaw)</strong><br />
                @Html.DisplayNameFor(model => model.Item1.Results.QuantResultSum): <strong> @Html.DisplayFor(model => model.Item1.Results.QuantResultSum)</strong><br />
                @Html.DisplayNameFor(model => model.Item1.Compound.CompoundDesc): <strong> @Html.DisplayFor(model => model.Item1.Compound.CompoundDesc)</strong><br />
                Employee: <strong> @Html.DisplayFor(model => model.Item1.Employee.EmpFirstName) @Html.DisplayFor(model => model.Item1.Employee.EmpLastName)</strong><br />
            </div>
        </div>
    </div>
</div>
<div>

</div>
<h2>Tests </h2>
<div class="col-sm-2 col-sm-offset-10 " style="text-align: right"><button class="btn-block" style="width: 175px;" onclick="location.href='@Url.Action("AddTest", new { iCode = Model.Item1.LT_Number })'">Add a Test</button></div>
<br />


    @foreach (var item in Model.Item2)
    {
        <div class="container2">
            

            <br />
            <div class="reviewtext1 review1">
                <span style="font-size: 18px">@Html.DisplayNameFor(modelItem => item.Tests.TestName): <strong> @Html.DisplayFor(modelItem => item.Tests.TestName)</strong></span>
                &nbsp;&nbsp;
                @Html.DisplayNameFor(modelItem => item.CompoundSequenceCode): <strong> @Html.DisplayFor(modelItem => item.CompoundSequenceCode)</strong>
                <br /><br />@{ var scheduled = item.DateScheduled.ToShortDateString();}
                @Html.DisplayNameFor(modelItem => item.DateScheduled): <strong> @Html.DisplayFor(modeItem => scheduled)</strong>
                <br />@{ var completed = item.DateCompleted.ToShortDateString();}
                @Html.DisplayNameFor(modelItem => item.DateCompleted): <strong> @Html.DisplayFor(modeItem => completed)</strong>

                <table class="col-sm-2 col-sm-offset-9 ">
                    <tr>
                        <td>
                            <button class="btn-block" onclick="location.href='@Url.Action("DeleteTest", new { iCode = item.CompoundSequenceCode })'">Delete</button>
                        </td>
                        <td>
                            <button class="btn-block" onclick="location.href='@Url.Action("EditTest", new { iCode = item.CompoundSequenceCode })'">Edit</button>
                        </td>


                    </tr>
                </table><br /><br />&nbsp;&nbsp;<br />
                @Html.DisplayNameFor(modelItem => item.Required) <strong> @Html.DisplayFor(modelItem => item.Required)</strong>
                &nbsp;&nbsp;
                @Html.DisplayNameFor(modelItem => item.RerunNeeded) <strong> @Html.DisplayFor(modelItem => item.RerunNeeded)</strong>
                &nbsp;&nbsp;
                @Html.DisplayNameFor(modelItem => item.AdditionalTests) <strong> @Html.DisplayFor(modelItem => item.AdditionalTests)</strong>
                &nbsp;&nbsp;
                @Html.DisplayNameFor(modelItem => item.Approved) <strong> @Html.DisplayFor(modelItem => item.Approved)</strong>
            </div>
            <div class="review2">




            </div>
        </div>
    }
<p>
    @Html.ActionLink("Back to All Work Orders", "Index", "WorkOrders")
</p>